# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8810ca4dffdfd6a2aa114db0a06a967ad86e16733808232b3a044352b387bcebe443832319eb34d9a205ac4e6fd6d2ee8771aeb46bf0f24127bfd86bfd73a36e

test:
  secret_key_base: 55075c307062212962f1fc02be828250ed835f5e796999198845c7ac518b0ef4566888b5d688ad8b2e84a5786dca31d3cbecf07e7411e6d6516559da1ef9918e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
